// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/GetImageCd/GetImageCd.proto

package go_micro_srv_GetImageCd2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GetImageCd2 service

type GetImageCd2Service interface {
	GetImageCd(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type getImageCd2Service struct {
	c    client.Client
	name string
}

func NewGetImageCd2Service(name string, c client.Client) GetImageCd2Service {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.GetImageCd2"
	}
	return &getImageCd2Service{
		c:    c,
		name: name,
	}
}

func (c *getImageCd2Service) GetImageCd(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "GetImageCd2.GetImageCd", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GetImageCd2 service

type GetImageCd2Handler interface {
	GetImageCd(context.Context, *Request, *Response) error
}

func RegisterGetImageCd2Handler(s server.Server, hdlr GetImageCd2Handler, opts ...server.HandlerOption) error {
	type getImageCd2 interface {
		GetImageCd(ctx context.Context, in *Request, out *Response) error
	}
	type GetImageCd2 struct {
		getImageCd2
	}
	h := &getImageCd2Handler{hdlr}
	return s.Handle(s.NewHandler(&GetImageCd2{h}, opts...))
}

type getImageCd2Handler struct {
	GetImageCd2Handler
}

func (h *getImageCd2Handler) GetImageCd(ctx context.Context, in *Request, out *Response) error {
	return h.GetImageCd2Handler.GetImageCd(ctx, in, out)
}
