// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/GetHouseInfo/GetHouseInfo.proto

package go_micro_srv_GetHouseInfo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GetHouseInfo service

type GetHouseInfoService interface {
	GetHouseInfo(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type getHouseInfoService struct {
	c    client.Client
	name string
}

func NewGetHouseInfoService(name string, c client.Client) GetHouseInfoService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.GetHouseInfo"
	}
	return &getHouseInfoService{
		c:    c,
		name: name,
	}
}

func (c *getHouseInfoService) GetHouseInfo(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "GetHouseInfo.GetHouseInfo", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GetHouseInfo service

type GetHouseInfoHandler interface {
	GetHouseInfo(context.Context, *Request, *Response) error
}

func RegisterGetHouseInfoHandler(s server.Server, hdlr GetHouseInfoHandler, opts ...server.HandlerOption) error {
	type getHouseInfo interface {
		GetHouseInfo(ctx context.Context, in *Request, out *Response) error
	}
	type GetHouseInfo struct {
		getHouseInfo
	}
	h := &getHouseInfoHandler{hdlr}
	return s.Handle(s.NewHandler(&GetHouseInfo{h}, opts...))
}

type getHouseInfoHandler struct {
	GetHouseInfoHandler
}

func (h *getHouseInfoHandler) GetHouseInfo(ctx context.Context, in *Request, out *Response) error {
	return h.GetHouseInfoHandler.GetHouseInfo(ctx, in, out)
}
